name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase repository name
        id: repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Set to true to push the image to a registry
          tags: ${{ steps.repo.outputs.lowercase }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.repo.outputs.lowercase }}:buildcache
          cache-to: type=registry,ref=${{ steps.repo.outputs.lowercase }}:buildcache,mode=max
