name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant permissions for the workflow to write to ghcr.io
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # This step converts the repository name to lowercase
      - name: Lowercase repository name
        id: repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      # Log in to the GitHub Container Registry
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses the lowercased repository name for all references
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.lowercase }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.lowercase }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.lowercase }}:buildcache,mode=max
